package com.dylan.model;

import java.io.Serializable;
import java.util.Date;

public class PortalDocument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.doc_id
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Long docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.doc_type
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Integer docType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.subject
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.doc_version
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Integer docVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.creator
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.created_time
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.last_modified_time
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.last_modifier
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private Long lastModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_document
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.doc_id
     *
     * @return the value of portal_document.doc_id
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Long getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.doc_id
     *
     * @param docId the value for portal_document.doc_id
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setDocId(Long docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.doc_type
     *
     * @return the value of portal_document.doc_type
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Integer getDocType() {
        return docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.doc_type
     *
     * @param docType the value for portal_document.doc_type
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setDocType(Integer docType) {
        this.docType = docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.subject
     *
     * @return the value of portal_document.subject
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.subject
     *
     * @param subject the value for portal_document.subject
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.doc_version
     *
     * @return the value of portal_document.doc_version
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Integer getDocVersion() {
        return docVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.doc_version
     *
     * @param docVersion the value for portal_document.doc_version
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setDocVersion(Integer docVersion) {
        this.docVersion = docVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.creator
     *
     * @return the value of portal_document.creator
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.creator
     *
     * @param creator the value for portal_document.creator
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.created_time
     *
     * @return the value of portal_document.created_time
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.created_time
     *
     * @param createdTime the value for portal_document.created_time
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.last_modified_time
     *
     * @return the value of portal_document.last_modified_time
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.last_modified_time
     *
     * @param lastModifiedTime the value for portal_document.last_modified_time
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.last_modifier
     *
     * @return the value of portal_document.last_modifier
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public Long getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.last_modifier
     *
     * @param lastModifier the value for portal_document.last_modifier
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setLastModifier(Long lastModifier) {
        this.lastModifier = lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_document
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PortalDocument other = (PortalDocument) that;
        return (this.getDocId() == null ? other.getDocId() == null : this.getDocId().equals(other.getDocId()))
            && (this.getDocType() == null ? other.getDocType() == null : this.getDocType().equals(other.getDocType()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getDocVersion() == null ? other.getDocVersion() == null : this.getDocVersion().equals(other.getDocVersion()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getLastModifiedTime() == null ? other.getLastModifiedTime() == null : this.getLastModifiedTime().equals(other.getLastModifiedTime()))
            && (this.getLastModifier() == null ? other.getLastModifier() == null : this.getLastModifier().equals(other.getLastModifier()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_document
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDocId() == null) ? 0 : getDocId().hashCode());
        result = prime * result + ((getDocType() == null) ? 0 : getDocType().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getDocVersion() == null) ? 0 : getDocVersion().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getLastModifiedTime() == null) ? 0 : getLastModifiedTime().hashCode());
        result = prime * result + ((getLastModifier() == null) ? 0 : getLastModifier().hashCode());
        return result;
    }
}