package com.dylan.model;

import java.io.Serializable;

public class PortalDocumentWithBLOBs extends PortalDocument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.subject_zh_tw
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private String subjectZhTw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.subject_zh_cn
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private String subjectZhCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.content
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.content_zh_tw
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private String contentZhTw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_document.content_zh_cn
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private String contentZhCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_document
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.subject_zh_tw
     *
     * @return the value of portal_document.subject_zh_tw
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public String getSubjectZhTw() {
        return subjectZhTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.subject_zh_tw
     *
     * @param subjectZhTw the value for portal_document.subject_zh_tw
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setSubjectZhTw(String subjectZhTw) {
        this.subjectZhTw = subjectZhTw == null ? null : subjectZhTw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.subject_zh_cn
     *
     * @return the value of portal_document.subject_zh_cn
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public String getSubjectZhCn() {
        return subjectZhCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.subject_zh_cn
     *
     * @param subjectZhCn the value for portal_document.subject_zh_cn
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setSubjectZhCn(String subjectZhCn) {
        this.subjectZhCn = subjectZhCn == null ? null : subjectZhCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.content
     *
     * @return the value of portal_document.content
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.content
     *
     * @param content the value for portal_document.content
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.content_zh_tw
     *
     * @return the value of portal_document.content_zh_tw
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public String getContentZhTw() {
        return contentZhTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.content_zh_tw
     *
     * @param contentZhTw the value for portal_document.content_zh_tw
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setContentZhTw(String contentZhTw) {
        this.contentZhTw = contentZhTw == null ? null : contentZhTw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_document.content_zh_cn
     *
     * @return the value of portal_document.content_zh_cn
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public String getContentZhCn() {
        return contentZhCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_document.content_zh_cn
     *
     * @param contentZhCn the value for portal_document.content_zh_cn
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    public void setContentZhCn(String contentZhCn) {
        this.contentZhCn = contentZhCn == null ? null : contentZhCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_document
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PortalDocumentWithBLOBs other = (PortalDocumentWithBLOBs) that;
        return (this.getDocId() == null ? other.getDocId() == null : this.getDocId().equals(other.getDocId()))
            && (this.getDocType() == null ? other.getDocType() == null : this.getDocType().equals(other.getDocType()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getDocVersion() == null ? other.getDocVersion() == null : this.getDocVersion().equals(other.getDocVersion()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getLastModifiedTime() == null ? other.getLastModifiedTime() == null : this.getLastModifiedTime().equals(other.getLastModifiedTime()))
            && (this.getLastModifier() == null ? other.getLastModifier() == null : this.getLastModifier().equals(other.getLastModifier()))
            && (this.getSubjectZhTw() == null ? other.getSubjectZhTw() == null : this.getSubjectZhTw().equals(other.getSubjectZhTw()))
            && (this.getSubjectZhCn() == null ? other.getSubjectZhCn() == null : this.getSubjectZhCn().equals(other.getSubjectZhCn()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getContentZhTw() == null ? other.getContentZhTw() == null : this.getContentZhTw().equals(other.getContentZhTw()))
            && (this.getContentZhCn() == null ? other.getContentZhCn() == null : this.getContentZhCn().equals(other.getContentZhCn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_document
     *
     * @mbggenerated Tue Nov 12 16:31:58 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDocId() == null) ? 0 : getDocId().hashCode());
        result = prime * result + ((getDocType() == null) ? 0 : getDocType().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getDocVersion() == null) ? 0 : getDocVersion().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getLastModifiedTime() == null) ? 0 : getLastModifiedTime().hashCode());
        result = prime * result + ((getLastModifier() == null) ? 0 : getLastModifier().hashCode());
        result = prime * result + ((getSubjectZhTw() == null) ? 0 : getSubjectZhTw().hashCode());
        result = prime * result + ((getSubjectZhCn() == null) ? 0 : getSubjectZhCn().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getContentZhTw() == null) ? 0 : getContentZhTw().hashCode());
        result = prime * result + ((getContentZhCn() == null) ? 0 : getContentZhCn().hashCode());
        return result;
    }
}